services:
  post-service-db:
    image: postgres
    container_name: post-service-db
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5001:5432"
    networks:
      - internal

  post-service:
    env_file: ".env"
    build:
      context: ./posts-service
      dockerfile: Dockerfile
    container_name: post-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://post-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal
    depends_on:
      - post-service-db

  comment-service-db:
    image: postgres
    container_name: comment-service-db
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5002:5432"
    networks:
      - internal

  comment-service:
    build:
      dockerfile: Dockerfile
      context: ./comment-service
    container_name: comment-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://comment-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - POST_VALIDATION_SERVICE_ADDRESS=post-service
      - POST_VALIDATION_SERVICE_PORT=9001
    ports:
      - "4002:4002"
    networks:
      - internal
    depends_on:
      - comment-service-db

  account-service-db:
    image: postgres
    container_name: account-service-db
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5003:5432"
    networks:
      - internal

  account-service:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: ./account-service
    container_name: account-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://account-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - TOKEN_SERVICE_ADDRESS=auth-service
      - TOKEN_SERVICE_PORT=9005
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "4003:4003"
      - "9003:9003"
    depends_on:
      - account-service-db
    networks:
      - internal

  email-service:
    env_file:
      - .email-env
    build:
      dockerfile: Dockerfile
      context: ./email-service
    container_name: email-service
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "4004:4004"
    depends_on:
      - kafka
    networks:
      - internal

  auth-service-db:
    image: postgres
    container_name: auth-service-db
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5005:5432"
    networks:
      - internal

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - JWT_SECRET=eqZBWm4S1EqxNKaNuwBJNFzXIOTYQAXdaoOrbUTQS1Q=
      - TOKEN_SERVICE_ADDRESS=account-service
      - TOKEN_SERVICE_PORT=9003
    ports:
      - "4005:4005"
      - "9005:9005"
    networks:
      - internal
    depends_on:
      - auth-service-db

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
    networks:
      - internal

networks:
  internal:
    driver: bridge